# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-17 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('profission', models.CharField(max_length=100, verbose_name='profissão')),
                ('twitter', models.CharField(max_length=120, verbose_name='Twitter')),
                ('facebook', models.CharField(max_length=120, verbose_name='Facebook')),
                ('linkendin', models.CharField(max_length=120, verbose_name='LinkendIn')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='sitio/images', verbose_name='imagem')),
            ],
        ),
    ]
